apiVersion: apps/v1
kind: Deployment
metadata:
  name: segments-ui
  labels:
    app: segments-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: segments-ui
  template:
    metadata:
      labels:
        app: segments-ui
    spec:
      containers:
      - name: segments-ui
        image: dhavelock/segments-ui:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_STRAVA_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: segments-api-secret
              key: segments-api-strava-client-id
        - name: REACT_APP_GOOGLE_MAPS_API_KEY
          value: AIzaSyCOfdNF9WDSN7mGltPXo8yqugi5zlnvZ0g
        - name: REACT_APP_API_ACTIVITIES_PATH
          value: '/api/activities'
        - name: REACT_APP_API_AUTHORIZE_PATH
          value: '/authorize/token'
        - name: REACT_APP_UI_REDIRECT_PATH
          value: '/explorer'
        - name: REACT_APP_STRAVA_AUTH_URL
          value: 'https://www.strava.com/oauth'
        - name: REACT_APP_API_BASE_URL
          value: 'http://127.0.0.1:8080'
---
apiVersion: v1
kind: Service
metadata:
  name: segments-ui-service
spec:
  selector:
    app: segments-ui
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
