apiVersion: v1
kind: Secret
metadata:
  name: segments-ui-secret
type: Opaque
data:
  segments-ui-strava-client-id: NjkyOTM=
  segments-ui-google-maps-api-key: QUl6YVN5Q09mZE5GOVdEU043bUdsdFBYbzh5cXVnaTV6bG52WjBn
