name: Snyk IaC

on:
  push:
    branches: [ master ]

jobs:
  snyk-iac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snyk/actions/setup@master

      - name: Run Snyk to check configuration files for security issues
        continue-on-error: true
        run: snyk iac test --sarif > snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif